### PR TITLE
modified text to VOICEMAIL OK, ID OK.

### PR DESCRIPTION
**Pull request by itsWill**
I rule and have completed some work on Case Manager that's ready for review!

easy one line text change from VOICEMAIL OK, to VOICEMAIL OK, ID OK

@colinxfleming 

It relates to the following issue #s: 

Fixes https://github.com/colinxfleming/dcaf_case_management/issues/674

### CODE REVIEW

**Comment by colinxfleming** [comment]
Change renders cleanly. Thanks again @itsWill !

screen shot 2016-10-23 at 10 33 22 pm

**Comment by mebates** [comment]
What does it look like on the Call List page?

**Comment by colinxfleming** [comment]
Code on the call list page is unaffected, still looks like so:

screen shot 2016-10-26 at 12 52 16 am

**Comment by mebates** [comment]
How about right below the modal? I was thinking about the first entry - looks like it's a dropdown now.

**Pull request merged**
