### PR TITLE
Alter Last Menstrual Period in Pregnancy Edit View

### LINKED ISSUE #185: Make Pregnancy#last_menstrual_period_time editable/render in a friendly way
screen shot 2016-03-27 at 7 29 07 pm

Menstrual period there in top-center is terrifying. Let's adjust that so that it's a human-readable and human-editable date. 

Probably this involves turning it into a date from a datetime, and adding a datepicker.

### LINKED ISSUE #186: Represent all of lmp_type, lmp_weeks, and lmp_time in the pregnancy edit page
These three attributes all exist in the model -- we should figure out how to represent them accurately and cleanly on the pregnancy edit page (located in `_patient_dashboard.html.erb`). 

Likely we'll need to get @NerdyGirl537 or @lwaldsc to weigh in on exact intended behavior here! But my guess is that we'll be collapsing them into one and inferring one (probably `lmp_weeks`) from the other (`lmp_time`). 

After figuring out the answer to the question, we should make appropriate frontend changes to the patient dashboard partial.

### LINKED ISSUE #246: Add status to table_content partial
In the designs (see https://projects.invisionapp.com/share/6757W6WFJ#/screens/115983262) we have a status field as part of the stock content. Let's add that in, following the designs for how it should look. 

These rollups come from the `table_content` partial in the dashboards -- we should make the edits there. (We also need a few of the partials edited to all use the same header columns -- see #214)

We can stub with just 'Status' and the words `Status Here` until #244 is ready to go.

### LINKED ISSUE #247: Add status to pregnancy edit view
Per the designs from @mebates , let's add status to the pregnancy edit view. 

image

We should add status to the top dashboard. This particular portion is in `app/views/pregnancies/_patient_dashboard.html.erb` I believe.

Similar to #246, we can just stub with sample text until #241 is ready to go.

### PR DESCRIPTION
**Pull request by colinxfleming**
Takes a stab at straightening out LMP in the view. In this iteration it looks as follows:

screen shot 2016-04-02 at 1 50 48 pm

The changes are stripping LMP as a date and replacing it with a weeks/days breakout, and then adding a readonly field that compares LMP on intake to the current date. 

(There are some less interesting/client facing edits to the pregnancy model, strong params, etc as well. And this isn't passing tests quite yet.) 

@lwaldsc @NerdyGirl537 can you all review and let me know what you think? Specifically interested in whether this fits into how LMP tends to be used on the fly when CM-ing. 

Fixes #185 
Fixes #186 
Fixes #247 
Fixes #246

### CODE REVIEW

**Comment by lwaldsc** [comment]
This is great! 

Would it be possible to split that bottom read only to LMP W/D into today's date and date of appointment when inserted into the appropriate field? I know it's a bit more coding but would be useful.

**Comment by colinxfleming** [comment]
I bet that's doable but not quite sure how it should play out. Any chance I
could get you to draw me a picture or break that into specific fields?

Otherwise we can discuss on Wednesday when we have everyone in the room
next.

**Comment by colinxfleming** [comment]
@mebates will want to touch this too since it's got design implications, so let's temporarily punt on this until Wednesday.

**Comment by mebates** [comment]
If this is what the CMs want, let's do it!

But, just to speak to the original design: we had envisioned the date and weeks drop down to have a relationship. So, if the patient says "April 4" you can put that in and it will show X weeks from the date you put in. Or, if she says "10 weeks", you can put that in the drop down and the date will update to 10 weeks before. Then the weeks drop down would need to automagically update when each week ticks by. Which is maybe the flaw in our plan.

**Comment by colinxfleming** [comment]
Let's make sure we talk about this on Wednesday to put a nail in it!

**Comment by colinxfleming** [comment]
Have this approximately sorted out now. Still TK: 

* Removing depreciated fields in pregnancy model 
* Making some of that stuff private
* Getting the helper text to spill over 
* Adjusting seeds to create someone who's at a different status for smoke testing
* Get the actual pregnancy fields to properly render
* Get approx gestation at intake to work

**Comment by colinxfleming** [comment]
This needs a refactor still and definitely needs testing, but here's an early draft of what it looks like from the main page and from the pregnancy view: 

screen shot 2016-04-28 at 8 44 23 pm

screen shot 2016-04-28 at 8 44 44 pm

**Comment by colinxfleming** [comment]
The major backend additions to this are going to wind up being the existence of `last_menstrual_period_helper.rb` and changes to the `pregnancy` model. The end result of that will be convenience methods for display of LMP in weeks and days according to two different dates (one, date of pregnancy creation/initial call, and two, date of appointment). (Also testing!)

**Comment by colinxfleming** [comment]
Declaring victory finally!

**Pull request merged**
