### PR TITLE
Add styling to new modal dialog

### LINKED ISSUE #737: Pledge button & modal styling
Create CSS styles for Pledge button and pledge modal

### PR DESCRIPTION
**Pull request by mchelen**
fixes #737

### CODE REVIEW

**Comment by colinxfleming** [comment]
Awesome, thanks @mchelen ! Looks like this includes a start on @mebates ' design requests for the buttons as follows:

* Next button should be purple
* Previous button should be white outlined with purple
* Cancel should be a red link
* Numbers at the top should be purple

The test that's failing because the elements it was looking for don't exist anymore (the actual failure in `test/integration/pledge_fulfillment_test.rb`). Here's a drop in replacement for that entire test which should get it back to green:

```
    it 'should show a link to the pledge fulfillment tab after pledge sent' do
      find('#submit-pledge-button').click
      find('#pledge-next').click
      find('#pledge-next').click
      check 'I sent the pledge'
      find('#pledge-next').click
      visit authenticated_root_path
      visit edit_patient_path @patient

      assert has_link? 'Pledge Fulfillment'
      click_link 'Pledge Fulfillment'
      assert has_text? 'Procedure date'
      assert has_text? 'Check #'
    end
```

**Comment by colinxfleming** [comment]
I'm gonna go ahead and close the other pull request in #787 , and we can fix #612 and #737 in one fell swoop with this once the styling is set.

I love what a collaborative team effort this has been. An example of this project at its absolute finest, I think.

**Comment by mchelen** [comment]
Ok the CSS has been updated with these changes. Took a best guess on hover & active colors.

image

**Comment by mchelen** [comment]
Increased modal padding per @mebates 
image

**Comment by colinxfleming** [comment]
@mchelen aside from getting the tests to pass (which I'm more than happy to handle), is the styling all good?

**Comment by mchelen** [comment]
@colinxfleming Yup it's ready! I got that test you posted updated as well :+1:

**Comment by colinxfleming** [comment]
@mchelen you are a national treasure. This is a real beaut and I'm super excited to roll it out this weekend.

**Comment by mchelen** [comment]
Woohoo!

**Pull request merged**
