### PR TITLE
Added helper text to income field on patient edit form

### LINKED ISSUE #460: Add helper text for income
From #405 - 

> 7- Add helper text where appropriate, i.e., for income field to explain what type of income is included. [1 user] 

Tagging in @lwaldsc @NerdyGirl537 @mebates @eheintzelman - 
- What should we make helper text for? 
- What copy be in the helper text?
- What is in the spreadsheet that we can crib from?

### PR DESCRIPTION
**Pull request by vincecampanale**
I rule and have completed some work on Case Manager that's ready for review!

(brief, plain english overview of your changes here)

This pull request makes the following changes:
* Adds helper text underneath income field on patient edit form 

(If there are changes to the views, please include a screenshot so we know what to look for!)

It relates to the following issue #s: 
* Fixes #460

### CODE REVIEW

**Comment by mebates** [comment]
@vincecampanale could you please drop a screengrab in here? much appreciated!

**Comment by vincecampanale** [comment]
@mebates Sorry about that! Here they are. The specific change is shown in the screen grab with just the Income field. The way it looks in the bigger picture is shown with the entire patient info screenshot. 
Patient info
Income field

**Comment by mebates** [comment]
Looks great, thank you!

**Comment by colinxfleming** [comment]
:shipit:

**Comment by colinxfleming** [comment]
thanks again @vincecampanale ! Appreciate your honing in on this a bunch.

**Comment by vincecampanale** [comment]
no problem @colinxfleming thanks for working with me - I'm learning a lot!

**Pull request merged**
