### PR TITLE
use automated build container image

### LINKED ISSUE #491: Use docker hub automated build for container image
https://hub.docker.com/r/mchelen/dcaf_case_management/

### PR DESCRIPTION
**Pull request by mchelen**
I rule and have completed some work on Case Manager that's ready for review!
- use docker hub automated build 

This pull request makes the following changes:
- create an automated build on docker hub
- point the `docker-compose.yml` file to use the built container
- update readme to deprecate `build` step

It relates to the following issue #s: 
- Fixes #491

You still need to create an automated build that points to this repo `colinxfleming/dcaf_case_management` so any updates will be automatically included in the built container: https://www.brianchristner.io/how-to-automate-docker-builds-end-to-end/ (just the first part "Create an Automated Build Docker Repository")

Then change the container name in `docker-compose.yml` and voila!

### CODE REVIEW

**Comment by colinxfleming** [comment]
This is sick, thanks @mchelen ! Had no idea docker could do this, and that absolutely rules. 

I'm going to let this marinate until after the meeting on Tuesday, and then we can get this going.

**Comment by colinxfleming** [comment]
@mchelen I've set some stuff up on my end at docker-hub! When you get a sec, want to try pulling down from `colinxfleming/dcaf_case_management` so we can make sure it works somewhere other than my machine?

**Comment by colinxfleming** [comment]
@mchelen bumping on this! Want to confirm it works for you before I hit the button.

**Comment by DarthHater** [comment]
A thought, you might want to create a codefordc user on Dockerhub to use rather than tie it to your personal accounts.

**Comment by DarthHater** [comment]
I was able to get @colinxfleming image running with some slight tweaks to the docker-compose file, nothing shocking. I'm not an expert on the app yet so I'm hesitant to say YEAH it's working but everything appears to be working fine.

**Comment by colinxfleming** [comment]
@DarthHater I think if it passes the majority of the test suite I feel good about that. (We have a few scrub integration tests that randomly choke.)

The organization user for this is a good call -- let me see what I can spin up in a hurry for dcaf. I've got a bunch of infra set up on that sort of level. 

Want to spin your edits to the compose file into a new PR and I'll merge it up?

**Comment by mchelen** [comment]
#720 looks good, @colinxfleming if you want to create an automated build on Docker hub then we can point the docker-compose.yml there and make sure everything is working nicely.

**Comment by DarthHater** [comment]
@colinxfleming my edits were just to test yours, nothing amazing. If you setup a more generic user I assume you or @mchelen can point the docker-compose file there?

**Pull request merged**
