### PR TITLE
added new types

### LINKED ISSUE #302: Implement type hierarchy for headers
From @mebates in #195, let's implement a standard type hierarchy for headers:

Details on the type hierarchy. The names I'm using may not align with the names you'll use in the HTML. All type is Source Sans Pro. (Sizes cribbed from here: https://cfpb.github.io/design-manual/identity/typography.html#web-hierarchy)

Display: 48 px / 60 px, 300 (Light)
H1: 34 px / 42 px, 400 (Regular)
H2: 26 px / 32 px, 400 (Regular)
H3: 22 px / 28 px, 400 (Regular)
H4: 14 px, 700 (bold), uppercase, 1 px letter-spacing

Body copy: 17 px / 26 px (1.5 em), 400 (Regular)

### PR DESCRIPTION
**Pull request by tingaloo**
I rule and have completed some work on Case Manager that's ready for review!

This PR change styles to reflect [CFPB guidelines](https://cfpb.github.io/design-manual/brand-guidelines/typography#web-hierarchy)

@mebates 
This is a *subtle* change because the font-sizes are already set somewhere in the project. Also a lot of time has passed since this issue opened.

I followed the CFPB guidelines as close as possible, only changing the font sizes made sense. I omitted font-weight changes because the current h1 is inversely weighted compared to CFSB. 

Only suggestion is to change from px to em for font-sizes.

For example,
```
h1 font-size: 3em;
h2 font-size: 2.215em;
h3 font-size: 1.625em;
h4 font-size: 1.375em;
h5 font-size: 1.125em;
```

This pull request makes the following changes:
* Organizes header font sizes

It relates to the following issue #s: 
* Fixes #302

### CODE REVIEW

**Comment by colinxfleming** [comment]
I <3 this. Thanks a ton for taking a look at this, @tingaloo ! One of my priorities as we continue to build out this app is to take major steps toward standardizing as much as possible, so I deeply appreciate this. 

@mebates can you review? It looks like the main changes are to the section headers in the patient edit view. Interested in your thoughts on `em` vs `px` as well, and whether we should explicitly declare anything else. 

**NEW VERSION**
screen shot 2016-10-22 at 12 51 12 am

screen shot 2016-10-22 at 12 51 20 am

Old version:
screen shot 2016-10-22 at 12 51 45 am

screen shot 2016-10-22 at 12 51 39 am

**Comment by mebates** [comment]
Looks good to me, and absolutely fine to convert to ems

**Comment by tingaloo** [comment]
@colinxfleming Glad to help. I noticed every stylesheet has defined their own font-sizes. :astonished:

CFPB had their font-size set to 16px, do you still want default font-size to 17px? 

And I can start pruning CSS on a page to page basis adhering to style hierarchy if that's what we need.

**Comment by mebates** [comment]
Default as 17 px is great. I'm guessing I was adhering more to US Web Design Standards hierarchy rather than CFPB at the time, but I'm not sure. Pruning CSS would be amazing, but @colinxfleming can weigh in on whether that is a priority!

**Comment by colinxfleming** [comment]
A CSS/assets cleanup is probably way, way, way overdue at this point, so call me in favor of that. @tingaloo I'm inclined to merge this PR so other folks can start enjoying the work here, and then turn you loose on the scss generally? 

The other frontend work besides building out templates mostly revolves around making our modals populate dynamically or building out scratch templates, so if you're interested in doing some SCSS cleanup specifically this I think this would be a good use of your time. (Though if you're interested in the other stuff that's solid too, let me know.)

**Comment by tingaloo** [comment]
sounds good to me, feel free to mention me if there's anything dynamic/state related.

**Comment by colinxfleming** [comment]
@tingaloo tagged you in on the async modal issue. I'll try to have that marked up in the next few days. Thanks for your work on this!

**Pull request merged**
