### PR TITLE
WIP - Add drag and drop functionality

### LINKED ISSUE #520: Make call list drag and droppable
During the pilot, @lwaldsc mentioned that she'd find it helpful to be able to rearrange her call list on the fly, rather than have them display in the order that they were added to her call list.

Open questions: 

* What's the use case for this? How do CMs organize their calls, and how should we reflect that in the app?
* What should we make them sortable on? Name, phone number, LMP, everything in the section?
* The possibility of doing this drag and drop was raised also -- is there something we get out of that which we don't get out of oneclick sorting?

### PR DESCRIPTION
**Pull request by colinxfleming**
So, totally sweet thing about mongodb is that it doesn't let you rearrange arrays. See this `wontfix` in the mongoid issue tracker -- https://jira.mongodb.org/browse/MONGOID-1706

At the very least, this PR adds an endpoint, and stubs out a model method that does the dirty work. I'll continue to haxx0r on this and see if I can get it to work cleanly. 

@mchelen - this sets up a route, `/users/:user_id/reorder_pregnancies`, that's expecting an array of ids. idk what the actual payload will look like, but I figured that was a good guess. Does collaborating on this feature branch sound like a plan? 

(fixes #520)

### CODE REVIEW

**Comment by colinxfleming** [comment]
Mongodb, it turns out, does not let you rearrange an array in place. So I hacked up a sort instead. In a nutshell, we'll use the contents of the split string `User#call_order` to sort `User#pregnancies`. Still TK is wiring up `_table_content` and making sure that `call_order` stays matched up against what's in the pregnancies array, but the really hard part of this was overcoming this mongodb limitation, and I feel pretty good about it working!

**Comment by mchelen** [comment]
How is JS managed in this app? If I want to add a Jquery plugin, where should that be done?

**Comment by colinxfleming** [comment]
We follow the rails standard -- external stuff in
vendor/assets/javascripts/, stuff we write ourselves in
app/assets/javascripts/. I assume you're asking about datatables-- stick it
in vendor if so. Lmk if I can clarify!

**Comment by mchelen** [comment]
@colinxfleming I'm going to try doing this with only jquery-ui to avoid adding too many js dependencies. I saw that the Gemfile includes `jquery-rails` so I tried adding https://github.com/joliss/jquery-ui-rails but I couldn't figure out how to rebuild the Gemfile.lock and doing something like `bundle update` caused errors like `You are trying to install in deployment mode after changing your Gemfile.`

**Comment by colinxfleming** [comment]
@mchelen `jquery-ui-rails` sounds good to me. Usually the ruby way to rebuild Gemfile.lock is a `bundle install`, give that a shot and let me know if that works. 

I'm going to bump the seedfile tonight to address yr issue from the other day, also.

**Comment by mchelen** [comment]
@colinxfleming Ok I got the gem installed, the issue was that editing the `Gemfile` and running `bundle install` would show an error:

```
$ bundle install                                                                        
You are trying to install in deployment mode after changing
your Gemfile. Run `bundle install` elsewhere and add the
updated Gemfile.lock to version control.

If this is a development machine, remove the /usr/src/app/Gemfile freeze 
by running `bundle install --no-deployment`.

You have added to the Gemfile:
* jquery-ui-rails
```

Oddly enough, running `bundle install --no-deployment` produced the same error.

It turned out I needed to modify `/root/.bundle/config` which had `BUNDLE_FROZEN: 1` and this needed to be set to `0` at which point `bundle install --no-deployment` worked successfully.

BTW this was all done using the docker container.

**Comment by colinxfleming** [comment]
@mchelen no idea about the gemfile freezing, that's pretty wild. Glad you were able to fix. 

I wired up the pregnancy call list rendering to drop in the relevant orders into the call list, so that's another part of this feature that's out of the way (I hope).

**Comment by colinxfleming** [comment]
Merged in @mchelen 's excellent work setting up the drag and drop here. 

Here's what the payload looks like:

```
Started PATCH "/users/57a65435b6305eb2f48b5f87/reorder_call_list" for ::1 at 2016-08-06 18:19:57 -0400
Processing by UsersController#reorder_call_list as JS
  Parameters: {"order"=>["57a66244b6305ebb38dcebf8", "57a66244b6305ebb38dcebfa", "57a66244b6305ebb38dcebf6", "57a66244b6305ebb38dcebfc", "57a66244b6305ebb38dcebfe"], "user_id"=>"57a65435b6305eb2f48b5f87"}
{"order"=>["57a66244b6305ebb38dcebf8", "57a66244b6305ebb38dcebfa", "57a66244b6305ebb38dcebf6", "57a66244b6305ebb38dcebfc", "57a66244b6305ebb38dcebfe"], "format"=>:js, "controller"=>"users", "action"=>"reorder_call_list", "user_id"=>"57a65435b6305eb2f48b5f87"}
```

Remaining trouble spots: 
* figure out why call list stuff isn't being updated (probably a strong params issue tbh
* parse the payload correctly
* integration test?

**Comment by mchelen** [comment]
@colinxfleming @mebates Ok great! Let me know if there is anything I can do to help. I pushed a few more CSS tweaks, but it would be great to have the design reviewed.

**Comment by colinxfleming** [comment]
Brought everything up to speed. Here's approx where this is at: 

* We can reorder!
* And it saves!
* And when a patient moves down to completed calls it doesn't choke!
* And when someone's removed it doesn't choke!

But: 
* If you add a new patient and refresh it, they disappear; need to figure out a way to dump anyone in the call list but not call order at the tail end
* The test suite needs a refresher
* Could use a readability refactor

@mchelen I'm super close on this. Probably will be able to finish it off next time I sit down to work on it.

**Comment by colinxfleming** [comment]
@mchelen I figured out the magic sort method after working on this on a decent night's sleep! Just have to remix the tests a little bit and we're all clear. 

@lwaldsc thanks to @mchelen 's remarkable frontend work, you're getting your wish of drag and drop.

**Comment by colinxfleming** [comment]
Last remaining piece here is to get the controller test passing and then I think we can merge.

**Comment by colinxfleming** [comment]
I have no earthly idea how to write integration tests with capybara for drag and drop, unfortch, so I'm going to backlog that for after this release. See #572.

@mchelen going to let this marinate until you stamp it approved from your end, if that's cool. Thanks again for doing the js piece of this and for pushing us to go big, truly this would not have happened without your initiative and elbow grease. Team CM is STOKED about it and they have you to thank.

**Comment by mchelen** [comment]
@colinxfleming Ok awesome, thats great to hear! Everything looks good to me, I'm seeing the d&d result being saved successfully. We can do design revisions in the future, but for now the styling looks decent & usable. :+1:

**Comment by colinxfleming** [comment]
Tests passing, things working, associated issue of integration tests backlogged -- I'm stamping as good to go. Thanks again @mchelen ! 

🎊

**Pull request merged**
