### PR TITLE
Add "Other medical issue" #631

### LINKED ISSUE #631: Add "Other medical issue"
Need to add "Other Health issues" checkbox to the special circumstances

### PR DESCRIPTION
**Pull request by KatSDC**
I rule and have completed some work on Case Manager that's ready for review!

I updated "Fetal anomaly" to "Fetal diagnosis" and added check boxes for "Other medical issue" and "Undocumented".

This pull request makes the following changes:
* Updated the special circumstances check boxes per user feedback

image

(If there are changes to the views, please include a screenshot so we know what to look for!)

It relates to the following issue #s: 
* Fixes #631

### CODE REVIEW

**Comment by KatSDC** [comment]
Kevin said that if we need to update previous entries for "Fetal anomaly" we will have to write a script to run through and update those entries. Is this something we want to do? I'd be happy to tackle that as well if the answer is yes. I'd just need to discuss with you what the production environment is running on.

**Comment by colinxfleming** [comment]
@KatSDC yeah, @Kevin-Wei is right, since we're storing this as an array of strings we'll want to bulk update it. If you want to dig into that I'd appreciate it -- you can probably whip something up using the `rails console` in a dev environment, if that makes sense -- but we can backlog it otherwise. 

Code looks good to me, I'll plan on having this deployed next Sunday during our regularly scheduled release window.

**Comment by colinxfleming** [comment]
ps thank you!! This is something a couple of CMs have asked for recently, esp as we've moved onto all three lines, so this is very timely.

**Comment by colinxfleming** [comment]
@KatSDC nice work up in here -- love how clean this turned out! I've spun out the task to update these entries in our prod db to #786.

**Pull request merged**
