### PR TITLE
[#345] generate pledge pdf

### LINKED ISSUE #345: Generate and download PDF of pledge
@lwaldsc @NerdyGirl537 can you all post a screenshot of a pledge form with fake information in it, so we can incorporate that into the pledge modal?

### PR DESCRIPTION
**Pull request by FeminismIsAwesome**
encapsulates this in a service
tests what i was willing to test via pledge_form_generator_test
please remove that if it turns out to be more trouble than its worth

This pull request makes the following changes:
* (your change here)
* (another change here)
* (etc)

This uses Prawn to generate documents, and PDF::Inspector::Text to convert that back into text I can test! yay testing?

The data that is flexible that I think they'd want dynamic based off the doc are in publically exposed methods in PledgeFormGenerator. PledgeFormGenerator#generate_pledge_pdf  has most of the text and just kind of throws everything together at once because MVP!

Not quite certain PledgeFormGenerator#patient_amount covers the right amount, feel free to let me know which fields it should be pulling from.

It relates to the following issue #s: 
* Fixes #345

### CODE REVIEW

**Comment by KatSDC** [comment]
Starting to review this PR!

**Comment by mebates** [comment]
@FeminismIsAwesome love your gh name and thanks for contributing! @KatSDC - is there any way you can rig this up so I can see it? Curious to know how it looks!  👀

**Comment by FeminismIsAwesome** [comment]
@mebates an example
[Angela Davis_pledge_form (1).pdf](https://github.com/colinxfleming/dcaf_case_management/files/823171/Angela.Davis_pledge_form.1.pdf)

**Comment by mebates** [comment]
Thanks @FeminismIsAwesome - do you think we can get it looking a bit more like the word file? Type is left aligned, certain portions are in bold, the boxed in area has sufficient padding around it, etc.

screen shot 2017-03-07 at 9 39 32 am

**Comment by colinxfleming** [comment]
I think if it's helpful we can take partial screenshots of the hard stuff
(the header, the remit at the bottom) and render the formatting heavy stuff
that way. I suspect doing it within the pdf library is a real pain, so
might easier to just cheat with that rather than fight with a dsl.

**Comment by colinxfleming** [comment]
Man @FeminismIsAwesome I am still in awe of you pulling this off, two weeks later. This is really incredible work. 

I'm going to knuckle down this weekend and rack the styling on this on Thursday/this weekend so we can have it available starting Sunday.

**Comment by colinxfleming** [comment]
I also missed that the name of the sample pledge person was 'Angela Davis'. Which I also love.

**Comment by FeminismIsAwesome** [comment]
@colinxfleming , aww you make me blush! I had meant to follow up and close it up, but have been busy moving so this fell by the wayside a bit. If you can wait until Thursday to try and give a spin at fixing it up, I could give another pass at the styling tommorrow since I'll have some time then.

Cheers,
Ian

**Pull request closed without merging**
