### PR TITLE
Use partial for multi step modals

### LINKED ISSUE #612: Standardize modal code & style
There are at least 2 different types of modals being used, such as the call modal and the pledge modal. Because they have different code & styling, they have different animation style, button styling, and only the call modal is successfully closed by clicking elsewhere on the screen.

The different types should be standardized, with code & styling reused between them.

### PR DESCRIPTION
**Pull request by colinxfleming**
I rule and have completed some work on Case Manager that's ready for review!

Takes @mchelen 's heroic work in #663 on rebuilding the pledge modal to be clean and fresh from the ground up and sands off a few rough edges; specifically, gets it into agreement with our improvements to the pledge modal, including displaying errors and required data, and not letting you go forward unless that data is present. 

This pull request makes the following changes:
* everything in #663 plus displaying necessary info

@mchelen can you approve? 

@mebates can you take a look when you get a chance and sign off? The things you requested in the other PR thread were `h4` headers (accounted for), some padding (not sure), and button styling follow what we do elsewhere (pretty sure this is accounted for).

When data isn't present:
screen shot 2016-12-24 at 1 36 57 pm

And when data is present, all three steps:

screen shot 2016-12-24 at 1 37 32 pm

screen shot 2016-12-24 at 1 37 38 pm

screen shot 2016-12-24 at 1 37 43 pm

It relates to the following issue #s: 
* Fixes #612

### CODE REVIEW

**Comment by mebates** [comment]
I was liking this better in #663 when it reflected our brand colors. 'Next' button should be purple, 'Previous' button should be white outlined with purple, and 'Cancel' should not be a button, but a red link. The numbers at the top should be purple too. Thanks!

**Comment by mchelen** [comment]
@mebates Oh yeah totally, this is pretty much just to do the underlying template logic and HTML. Then the CSS styling is probably a separate task #737

**Comment by mchelen** [comment]
@colinxfleming everything here looks good to me!

**Comment by colinxfleming** [comment]
Closing in favor of #809 , which just has the styling left before we're all good!

**Pull request closed without merging**
