### PR TITLE
Notes escape

### LINKED ISSUE #583: Notes bug: note cutting off on dashboard
The full note isn't showing from the dashboard: 

image

### PR DESCRIPTION
**Pull request by mchelen**
I rule and have completed some work on Case Manager that's ready for review!

This pull request makes the following changes:
* html encode notes content

It relates to the following issue #s: 
* Fixes #583

### CODE REVIEW

**Comment by colinxfleming** [comment]
@mchelen you are a treasure. Reviewing now.

**Comment by colinxfleming** [comment]
image

**Comment by colinxfleming** [comment]
The integration test is failing for a fake reason here. Merging.

**Comment by colinxfleming** [comment]
Just in case we ever have to revisit this, I did put some arbitrary javascript alerts in a note and it didn't trigger, so confirmed that this isn't injectable.

**Comment by mchelen** [comment]
two character commit ftw :smiley_cat:

**Pull request merged**
