### PR TITLE
Render clinic find info

### PR DESCRIPTION
**Pull request by colinxfleming**
This pull request makes the following changes:
* Integration with clinic_finder gem
* New route for this tool at /clinicfinder
* View for inputting patient zip + gestational age
* Renders as 2 tables the results from clinic_finder gem as Nearest Clinics and Most Affordable Clinics

screen shot 2017-03-05 at 3 19 57 pm

### CODE REVIEW

**Comment by colinxfleming** [comment]
@jingpei did all this !!!!!!!

**Comment by mebates** [comment]
omg :1st_place_medal: 
This is crazy!
I'm guessing that your last two commits made the names plain language. Did you add a dollar sign? So cool!!

**Comment by lwaldsc** [comment]
I'm so pumped this is a real live breathing thing. I just can't believe it.

**Comment by colinxfleming** [comment]
Next step here is to build it into the patient edit view somewhere, so CMS
have it available in conversations.

But I just want to say that Jing did an incredible job on setting this up
under a huge time crunch and I'm so impressed by her hard work and
willingness to tackle this, as well as the hard work of the team that built
the clinic finder gem.

**Pull request merged**
