### PR TITLE
[WIP] Use partial for multi step modals

### LINKED ISSUE #612: Standardize modal code & style
There are at least 2 different types of modals being used, such as the call modal and the pledge modal. Because they have different code & styling, they have different animation style, button styling, and only the call modal is successfully closed by clicking elsewhere on the screen.

The different types should be standardized, with code & styling reused between them.

### PR DESCRIPTION
**Pull request by mchelen**
Fixes #612 by using standard Bootstrap modal config

Todo:
- [x]  Pledge multipart modal
- [ ]  Submit pledge button CSS #737
- [ ] Update unit test

### CODE REVIEW

**Comment by colinxfleming** [comment]
yussssss

@mchelen let me know how I can be helpful on this!

**Comment by mchelen** [comment]
Ok, I have an initial working version of a multipart modal. @colinxfleming would love any feedback!

**Comment by colinxfleming** [comment]
@mchelen awesome my dude. I'll take a look tomorrow night or early Saturday, depending on when I catch up on sleep this weekend.

**Comment by colinxfleming** [comment]
@mchelen Confirm that this works on my machine! Love this cleanup. 

I'm super into this. I think it's a massive step forward in making this part of the code much more maintainable. 

If you're interested in continuing to abstract this a little further, you might consider putting some of the standard code in a helper -- see `notes_helper` for how we're currently doing this with note displays. This is kind of the rails standard way to abstract view code -- anything that's in a helper method is automatically made available in an ERB template. 

Anything in particular you'd like eyes on?

**Comment by mchelen** [comment]
@colinxfleming Ok cool, I mainly wanted a sanity check. I think the main question I had was whether to use another 3rd party lib like https://github.com/orige/jquery-bootstrap-modal-steps or https://github.com/ngzhian/multi-step-modal or if that's overkill for our usage.

Also should we make any progress on the content of the submit pledge modal? I'm not sure what it's going to end up doing, so I'd like to implement something that won't interfere with its planned functionality.

Finally, I need to take a look at how this code affects the current unit test, and update the test appropriately.

**Comment by mchelen** [comment]
@colinxfleming Hey I'm not going to make it to the meetup tonight, but if you have any general thoughts on this that would be great. I could polish it up and merge as-is, or try to create a helper, or wait until more of the pledge modal itself is built out. Let me know what sounds best.

**Comment by mebates** [comment]
What does it look like?

**Comment by colinxfleming** [comment]
@mebates a pair of screenshots of the standardized styling for yr review:

screen shot 2016-10-22 at 12 20 26 am

screen shot 2016-10-22 at 12 21 27 am

@mchelen the design stuff is @mebates call but I think that we'd get a *lot* of utility out of this being a helper. I'm sure that having a straightforward way to stitch together modals with the exact same styling and function every time is going to be something that saves us a lot of time down the road. So that's my preference. 

I'm inclined to skip the 'create pledge preview' part for the time being. 

Thanks a ton for continuing to plug away at this -- again, this takes something we built out REALLY fast and makes it significantly more maintainable down the line. So Future Us is very thankful for your hard work here.

**Comment by mebates** [comment]
I would suggest adding styling to the title to the modal - here it's "Create Pledge" - by making it an H4. Also more padding around the edges, maybe 15 to 20 px? And, are we using a standard for our button styling (US Web Design Standards or CFPB?). If so, the buttons should be the same size.

**Comment by colinxfleming** [comment]
@mchelen is the strategy we talked about panning out okay? Let me know if I can help you hack thru anything!

**Comment by mchelen** [comment]
@colinxfleming as of https://github.com/colinxfleming/dcaf_case_management/pull/663/commits/ab94d59a6f0f818251c610bffa61b21d09fab316 it seems to only be showing the second chunk of HTML, and it's being escaped:
```
&lt;/div&gt;

      &lt;div class=&quot;modal-footer&quot;&gt;
        &lt;button type=&quot;button&quot; class=&quot;btn btn-default js-btn-step pull-left&quot; data-orientation=&quot;cancel&quot; data-dismiss=&quot;modal&quot;&gt;&lt;/button&gt;
        &lt;button type=&quot;button&quot; class=&quot;btn btn-warning js-btn-step&quot; data-orientation=&quot;previous&quot;&gt;&lt;/button&gt;
        &lt;button type=&quot;button&quot; class=&quot;btn btn-success js-btn-step&quot; data-orientation=&quot;next&quot;&gt;&lt;/button&gt;
      &lt;/div&gt;
    &lt;/div&gt;
  &lt;/div&gt;
&lt;/div&gt;
```

Trying to figure out what is going wrong...

**Comment by colinxfleming** [comment]
Ah, rails can be a real ding dong about escaping things -- it's one of
those safety valves built in to prevent XSS and stuff.

Check out `content_tag` and `tag` -- a couple livefire examples you can
probably model off are in
https://github.com/colinxfleming/dcaf_case_management/pull/716/files The
actual module documentation is here:
http://api.rubyonrails.org/classes/ActionView/Helpers/TagHelper.html

In a pinch, you can also just mark a particular string `'<div>lots of
code</div>'.html_safe` and it'll escape and render correctly.

On Mon, Nov 7, 2016 at 9:42 AM Mike Chelen <notifications@github.com> wrote:

@colinxfleming <https://github.com/colinxfleming> as of ab94d59
<https://github.com/colinxfleming/dcaf_case_management/pull/663/commits/ab94d59a6f0f818251c610bffa61b21d09fab316>
it seems to only be showing the second chunk of HTML, and it's being
escaped:

&lt;/div&gt;

      &lt;div class=&quot;modal-footer&quot;&gt;
        &lt;button type=&quot;button&quot; class=&quot;btn btn-default
js-btn-step pull-left&quot; data-orientation=&quot;cancel&quot;
data-dismiss=&quot;modal&quot;&gt;&lt;/button&gt;
        &lt;button type=&quot;button&quot; class=&quot;btn btn-warning
js-btn-step&quot;
data-orientation=&quot;previous&quot;&gt;&lt;/button&gt;
        &lt;button type=&quot;button&quot; class=&quot;btn btn-success
js-btn-step&quot; data-orientation=&quot;next&quot;&gt;&lt;/button&gt;
      &lt;/div&gt;
    &lt;/div&gt;
  &lt;/div&gt;
&lt;/div&gt;

Trying to figure out what is going wrong...

—
You are receiving this because you were mentioned.


Reply to this email directly, view it on GitHub
<https://github.com/colinxfleming/dcaf_case_management/pull/663#issuecomment-258853067>,
or mute the thread

**Comment by mchelen** [comment]
@DarthHater's partial looks good! I added in the content for the pledge modal, and renamed the partial to `multi_modal` so we can distinguish between single screen modal dialogs.

This PR should be ready now, except for updating tests.

**Comment by colinxfleming** [comment]
ahhhh I love this so much. Thanks a ton @mchelen -- this looks pretty sharp to me. Want me to handle getting the integration test to pass?

**Comment by mchelen** [comment]
Feel free to tackle it if you have the chance, otherwise I'll work on it
when I can - I'm unfamiliar with the type of tests used.

**Comment by colinxfleming** [comment]
@mchelen so I think that test failure is flagging something legit -- if I do `rake db:seed`, head to Patient 0 from the call list, and click on `submit pledge`, here's what I get: 

image

On reload, I can get it to populate as it's supposed to be: 

image

Can you recreate this? 

I'll wrench around and see if there's a straightforward fix in 15m.

**Comment by colinxfleming** [comment]
Also want to note that this looks like a JS thing, as it looks like the modal content itself is getting populated into the dom? 

image

**Comment by DarthHater** [comment]
FWIW I had that same issue @colinxfleming when I made the partial. I didn't debug it because I figured @mchelen would know better about why it was happening?

**Comment by mchelen** [comment]
Hmm ok, let me see if I can debug this.

**Comment by mchelen** [comment]
@colinxfleming @DarthHater Ok I think I found the problem, Rails does this thing called Turbolinks https://geekmonkey.org/2012/09/introducing-turbolinks-for-rails-4-0/ which means the normal document ready event is not fired on each page load http://stackoverflow.com/questions/18770517/rails-4-how-to-use-document-ready-with-turbo-links

Hopefully fixed now...

**Comment by DarthHater** [comment]
Deferring to @colinxfleming , I wouldn't know good client side with rails if it stepped on my face

**Comment by colinxfleming** [comment]
Oh god. There was like a solid three months of my life where every problem I ran into was because of turbolinks in one way or another. I apologize for not ripping this out of our gemfile months ago. 

If winds up not being resolved we should remove turbolinks and see if that fixes it. 

@mchelen I'll review this tonight -- thanks my dude!

**Comment by mchelen** [comment]
@colinxfleming Hey I can't come tonight, but I think any JS loading issues have been resolved. We do have a merge conflict though. The issue is the validation logic attached to the form button. Let me know what approach we want to take with this and I'll try to help.

**Comment by colinxfleming** [comment]
@mchelen I think I have this good to go! (Other than a design review which I think can wait.) Resolved the conflicts that were introduced when we started enforcing data presence on some fields in order to submit a pledge. I'll spin up a separate pr for it.

**Comment by mchelen** [comment]
Closed in favor of #787

**Pull request closed without merging**
