### PR TITLE
Render other contact's name on call modal even if no number

### PR DESCRIPTION
**Pull request by valeriecodes**
Resolves: https://github.com/colinxfleming/dcaf_case_management/issues/758

Here are screenshots of the main cases:
No secondary contact (unchanged)
screen shot 2016-12-01 at 9 21 51 pm

Secondary contact name but no number
screen shot 2016-12-01 at 9 25 35 pm

Secondary contact name and number
screen shot 2016-12-01 at 9 25 19 pm

Secondary contact number but no name
screen shot 2016-12-01 at 9 36 57 pm

### CODE REVIEW

**Comment by colinxfleming** [comment]
@lwaldsc as the reporter of the bug in #758 can you approve?

**Comment by lwaldsc** [comment]
The No Name but Other Contact Number should also display the secondary
number.

Other than that, the screenshots look fantastic!! Thanks, @valeriecodes

**Comment by valeriecodes** [comment]
Thanks @lwaldsc . I updated the screenshots. Look good?

**Comment by colinxfleming** [comment]
I think if there are remaining parts of this they're related to copy rather than code, so I'm going to hit go. Thanks again for digging in here @valeriecodes !!

**Pull request merged**
