### PR TITLE
Add validation for uniqueness of primary_phone

### PR DESCRIPTION
**Pull request by jasonallenphotography**
I added model validations for patient uniqueness.

This pull request makes the following changes:
* Adds `uniqueness: true` to primary_phone validations

(If there are changes to the views, please include a screenshot so we know what to look for!)

It relates to the following issue #s: 
* Satisfies issue #620

### CODE REVIEW

**Comment by colinxfleming** [comment]
Thanks so much for handling this, @jasonallenphotography ! Really appreciate your fixing the tests as well! 

i'll test on my local machine tomorrow and merge.

**Comment by jasonallenphotography** [comment]
Happy to help. I'll be working on a few other outstanding issues over the weekend here!

**Comment by colinxfleming** [comment]
For posterity's sake, here's the command I used to find duplicates within our system (which I'm resolving by hand now, since there's only about six of them): 

`Patient.all.group_by(&:primary_phone).sort_by {|x| x.count}.map { |x| puts x[0].to_s + ":" + x[1].count.to_s if x[1].count > 1 }`

**Comment by colinxfleming** [comment]
Duplicate entries in prod are resolved except for one so this is ready to go. Merging.

**Pull request merged**
