### PR TITLE
Resolving issue #475.

### PR DESCRIPTION
**Pull request by MiroFurtado**
From #475 

Updated seeds.rb script to allow importing data from a csv file.
Model csv file can be found at db/patients.csv
Usage for set up is "rake db:seed FILENAME" or just "rake db:seed" to use the previously implemented functionality.

### CODE REVIEW

**Comment by MiroFurtado** [comment]
Honestly am not sure why this second commit fails the checks.

**Comment by MiroFurtado** [comment]
@colinxfleming Should I be putting all of these commits in the same pull request or spreading it out?

**Comment by colinxfleming** [comment]
Separate pull requests please! Separate PRs for separate features is super
helpful -- helps us keep work separate, gives us a better picture of where
stuff lays, and smaller PRs are way easier to merge.

**Comment by colinxfleming** [comment]
I see there's some work in here pertaining to importing -- clutch. Let's
talk about this at length at or after the meeting -- want to make sure you
have some sample data that we're importing, so you don't have to guess.

**Comment by MiroFurtado** [comment]
@colinxfleming I won't be at the meeting unfortunately so we can probably talk on slack. I have a little bit of random sample data I put together in patients.csv just to demo how the code works.

**Comment by MiroFurtado** [comment]
I am going to close this and implement my commits as different pull requests. My fault, @colinxfleming

**Pull request closed without merging**
