### PR TITLE
WIP - Excel import functionality

### PR DESCRIPTION
**Pull request by MiroFurtado**
From #475-- this implements the excel import. 
Updated seeds.rb script to allow importing data from a csv file.
Model csv file can be found at db/patients.csv
Usage for set up is "rake db:seed FILENAME" or just "rake db:seed" to use the previously implemented functionality.

### CODE REVIEW

**Comment by colinxfleming** [comment]
Thanks a ton for getting this started up! I'm gonna let this hang until tomorrow.

**Comment by MiroFurtado** [comment]
Sure! It might be helpful to know exactly what sort of information we want to be importing from excel/what the spreadsheet would look like. We should also put together a spreadsheet with more model data in it.

**Comment by NerdyGirl537** [comment]
Thoughts on import: We store city and state in the same cell.  They may or may not be separated by a comma.  Sometimes, there are multiple phone numbers in that cell.  The number of people in household isn't standardized -- sometimes it is a number; sometimes more details.

**Comment by colinxfleming** [comment]
Increasingly, I'm coming to think that this is a thing we do for the VA/MD release or a wider release. We have a limited time between now and release, and I think we should focus that on CM features rather than programmatic data backlog entry, a problem at which we can throw nontechnical person power. 

Sorry for giving you bad guidance on this @MiroFurtado ! Let's have this PR continue to sit for the time being in case we want to pick it up after August 22.

**Pull request merged**
