### PR TITLE
Create cm-workflow

### PR DESCRIPTION
**Pull request by lwaldsc**
Create rough explanation of case manager workflow, needs from patients and case managers, and data needed

### CODE REVIEW

**Comment by mebates** [comment]
where will this live?

**Comment by colinxfleming** [comment]
@mebates I think either some separate readme or the wiki would work, but I'd honestly leave it up to you. (This was a stab at #23, so wherever you think is a good place for that is cool with me.)

**Comment by colinxfleming** [comment]
@lwaldsc  talked to mollie and we're going to throw this in the wiki. Going to close without merging and put your work in a wiki page. Thanks so much for getting this going.

**Comment by colinxfleming** [comment]
Put in https://github.com/colinxfleming/dcaf_case_management/wiki/DCAF-101 ; closing PR.

**Pull request closed without merging**
