### PR TITLE
[Don't merge, utility] - Data entry form

### PR DESCRIPTION
**Pull request by colinxfleming**
I rule and have completed some work on Case Manager that's ready for review!

Adds a form matching the spreadsheet order for mass data entry, so we can punch in individual patients easier. 

TK testing and confirming that everything shows up right once entered. 

screen shot 2016-11-26 at 4 35 06 pm

### CODE REVIEW

**Comment by colinxfleming** [comment]
I hand-tested this and it looks good except for adding notes, so I added a quick and dirty redirect once people are entered. 

Probably won't be worth merging but will be nice to have on hand for data entry.

**Comment by NerdyGirl537** [comment]
@colinxfleming what instructions do I need to share with the volunteers for accessing this?

**Comment by colinxfleming** [comment]
To close the loop on this, I've emailed @NerdyGirl537 separately with details for mass entry. I'll make a note when I've deployed this. 

Note for self: Looking increasingly like merging to master is the right thing to do, and then turning it off in a separate PR.

**Comment by colinxfleming** [comment]
Drop of coverage isn't a serious problem due to this being adhoc. Ticket to close these routes once things are disabled is set. Merging.

**Pull request merged**
