### PR TITLE
Add bootstrap-toggle to new pregnancy partial

### LINKED ISSUE #365: Need 'Voicemail OK?' check box somewhere on the patient page
@dfelsent helped me realize that we don't have a 'Voicemail OK?' check box any where on the patient info pages. Can we add the check mark in on the Patient Info page? 

image

### PR DESCRIPTION
**Pull request by colinxfleming**
I rule and have completed some work on Case Manager that's ready for review!

@sco-bo I took yr PR and ran with a little bit. Couldn't quite get it to work on the pregnancy edit view (might be a bootstrap_forms gem issue?) so I stubbed it for the time being. Thanks for getting this going, my dude! Want to take a look at this and confirm that it makes sense and stuff?

screen shot 2016-06-26 at 2 25 59 pm

screen shot 2016-06-26 at 2 28 23 pm

This pull request makes the following changes:
* Finishes off adding pretty toggle switch to new pregnancy form
* Adds plain old boring checkbox to pregnancy edit view

It relates to the following issue #s: 
* Half-fixes #365

### CODE REVIEW

**Comment by colinxfleming** [comment]
(Safe to merge, the build is failing for a stupid reason.)

**Comment by colinxfleming** [comment]
Picks up the work by @sco-bo in #373

**Comment by sco-bo** [comment]
Hey @colinxfleming Thanks for cluing me in on the fix. Super helpful to know for the next time I work with JS/Bootstrap Toggle. Thanks!

**Comment by colinxfleming** [comment]
@sco-bo Like I have always said to anyone who will listen (including my mom), javascript is the devil! I feel like this encapsulates 50% of the problems I have with this kind of issue, haha.

**Pull request merged**
