### PR TITLE
Changed pregnancy edit view tab order

### LINKED ISSUE #451: Change order of tabs in pregnancy edit view
From #405 - 

> 7 - Change order of tabs to Patient information, Abortion Information, then notes.  [3 users]

The people have spoken, let's make this edit to `app/views/pregnancies/_menu`. Note that you'll also want to change it so that the active tab on page load is Patient Information. 

Straightforward fix! Marking beginner friendly and frontend.

### PR DESCRIPTION
**Pull request by MiroFurtado**
Fixes #451

### CODE REVIEW

**Comment by colinxfleming** [comment]
Thank you so much for knocking this out, @MiroFurtado ! Welcome to the project, we're glad to have you! 

Looks like this is failing CI with the following errors:

```
ERROR["test_0001_should alter the information", #<Class:0x007fc458370338>, 10.555818611999712]
 test_0001_should alter the information#UpdatePatientInfoTest::changing patient information (10.56s)
Capybara::ElementNotFound:         Capybara::ElementNotFound: Unable to find field "Secondary person"
            test/integration/update_patient_info_test.rb:69:in `block (2 levels) in <class:UpdatePatientInfoTest>'

 FAIL["test_0004_should let you click to patient information", #<Class:0x007fc458435a20>, 16.93567547299972]
 test_0004_should let you click to patient information#ShowPregnancyInformationTest::clicking between sections to see information (16.94s)
        Expected true to not be truthy.
        test/integration/show_pregnancy_information_test.rb:49:in `block (3 levels) in <class:ShowPregnancyInformationTest>'
        test/integration/show_pregnancy_information_test.rb:48:in `block (2 levels) in <class:ShowPregnancyInformationTest>'
```

The first one is a legit flag issue, the second one is just our test suite assuming that things are different on page load.

* For the first one, we'll need to change which section has the class `active` on page load from `#abortion_information` to `#patient_information`. This is pretty straightforward, just a matter of swapping it out in the respective partials in `app/views/pregnancies/{PARTIAL}`.

* For the first one, we'll want to adjust our tests to reflect the new behavior you're implementing. Specifically, let's adjust `should show abortion information on open` to `show patient information on open`, and use capybara to click the `abortion information` link. Let me know if I can clarify anything about this point.

LMK if I can unstick or clarify anything. Thanks again for popping this in, really appreciate it!

**Comment by MiroFurtado** [comment]
@colinxfleming Thanks! I think the change should be ready for a pull now.

**Comment by colinxfleming** [comment]
Thanks a ton, @MiroFurtado ! Will I be able to meet you at the code for DC meeting this week?

**Comment by MiroFurtado** [comment]
@colinxfleming I don't think I have enough experience to throw myself into Code for DC yet. I hardly know ruby.

**Comment by colinxfleming** [comment]
There are more than a few people on this project who aren't extremely ruby
savvy -- don't feel like you need to be some ascended rails master to hang
out and contribute. (Also, if you're interested in ruby, hanging out is a
pretty good way to start learning.)

**Pull request merged**
