### PR TITLE
587 footer

### LINKED ISSUE #587: Create a footer
Create a footer! And populate it with the following:

"Please send feedback or ideas for the CM App to DCAF.CMapp@gmail.com." (mailto link)

DCAF phone number, website
NAF phone number, website
onlinefaxes.com
+ <strike>link to User Manual in Crypto</strike> (later)

cc: @lwaldsc

### PR DESCRIPTION
**Pull request by jasonallenphotography**
I did some work on DCAF that's ready for review!

I built out a footer partial and inserted it into the application layout.

One minor issue that I'd like someone else's eyes on - test/integration/update_patient_info has a flunking test (#should alter the information), but I see that it's been flagged... pretty sure it's the test (master branch is flunking the same test locally for me), so if someone else could examine before merge I'd appreciate it!

This pull request makes the following changes:
* Adds a footer partial to layouts/application
* Styles elements of the footer

Preview of the addition:
screen shot 2016-09-05 at 9 17 23 pm

It relates to the following issue #s: 
* Fixes #587

### CODE REVIEW

**Comment by colinxfleming** [comment]
Tagging in @mebates @eheintzelman for review !

**Comment by colinxfleming** [comment]
Also, yeah, there's been a test that fails like half the time for no good reason for a little while. Sorry! I know it's a pain, am working on fixing it up.

**Comment by mebates** [comment]
looks good. thanks!

**Comment by colinxfleming** [comment]
Thanks again for this @jasonallenphotography !

**Pull request merged**
