### PR TITLE
fix #178

### LINKED ISSUE #178: Only display full call list toggle if there are 10+ calls
In `app/views/pregnancies/_call_log.html.erb`, there's a toggle button that displays the full set of calls instead of just limiting to the most recent 10. In the event that there aren't ten calls yet, let's make it not show up.

### PR DESCRIPTION
**Pull request by mchelen**

### CODE REVIEW

**Comment by colinxfleming** [comment]
Going to leave this open for now per discussion in #178, does that sound good to you @mchelen ?

**Comment by mchelen** [comment]
- Updated PR with suggestions from #178 
- Fixed logic for checking call count
- Moved button to bottom of list for better UX

**Comment by colinxfleming** [comment]
@mchelen this works perfectly, thanks so much for sticking with it! Would you mind doing me a solid and resolving the merge conflict in favor of the h1 with the `border-bottom title` class value, and then I'm going to merge this up!

:100:

**Comment by mchelen** [comment]
Ok I resolved the conflict and successfully merged in `master` branch, hope that's the right way to address it.

**Comment by colinxfleming** [comment]
That's dead on. Thanks a ton!

**Pull request merged**
