### PR TITLE
Add MIT license

### LINKED ISSUE #58: Add license
This is a great resource is one is needed: http://choosealicense.com/

### PR DESCRIPTION
**Pull request by colinxfleming**
Adds an MIT license and makes edits in the readme and the civic.json. 

@stvnrlly for yr review. 

Fixes #58

### CODE REVIEW

**Comment by stvnrlly** [comment]
LGTM, with one exception: the deprecated section is a little confusing. Is there any reason to keep it rather than just tossing it?

**Comment by colinxfleming** [comment]
@stvnrlly not quite sure which section you're referring to, can you comment on the line? 

FWIW The text in `LICENSE.txt` is copypasta straight from the choosealicense page.

**Comment by stvnrlly** [comment]
Ah, I'm talking about the `README`: https://github.com/colinxfleming/dcaf_case_management/blob/license/README.md#depreciated-readme-stuff.

**Comment by colinxfleming** [comment]
Ah, gotcha. You are right, that's probably no longer necessary since this
isn't Jekyll oriented anymore and we can ditch it.

**Pull request merged**
