### PR TITLE
Update Cloud9 Setup Instructions

### LINKED ISSUE #534: Have to install MongoDB, Bundler on Cloud9
Currently the instructions for working on this in Cloud9 seem to be out of date. I had to install another version of Ruby, then the Bundler gem, then install Mongo in the Cloud9 workspace.

### PR DESCRIPTION
**Pull request by benjamincrane**
I have completed some work on Case Manager that's ready for review!

This pull request makes the following changes:
* updates the setup instructions to get the page working on a Cloud9 workspace

It relates to the following issue #s: 
* Fixes #534

### CODE REVIEW

**Comment by colinxfleming** [comment]
Thanks a ton, @benjamincrane ! Really appreciate your keeping the readme up to date and strong.

@ewiggins I'm tagging you in to review. Can you replicate these steps in a new cloud9 environment? Let me know if you need a hand.

**Comment by ewiggins** [comment]
@colin Yep! I'll work on it tomorrow evening.

**Comment by benjamincrane** [comment]
Ah crud. I should have done a different branch or something for this commit. What's the git approved way to fix this? Close my pull request?

**Comment by benjamincrane** [comment]
Okay, I reverted my other commit and will commit that in a separate branch.

**Comment by colinxfleming** [comment]
Thanks @benjamincrane -- really appreciate your working thru that to keep
the PRs separate.

**Comment by ewiggins** [comment]
@colinxfleming This is good to go! The commands worked. Good job @benjamincrane!!! This issue reminded me that I wanted to add additional steps to the Cloud9 instructions for complete beginners so the process to get up and running on the project isn't such a pain for them. I'll work on that once issues #544 and #534 are closed in #549.

**Comment by colinxfleming** [comment]
Thanks a ton @benjamincrane and @ewiggins !

**Comment by benjamincrane** [comment]
It looks like my revert commit ended up overwriting this commit so I am submitting another pull request to fix that.

**Pull request merged**
