### PR TITLE
Ruby two dot four dot oh - Mergeable, plz test w/ me

### PR DESCRIPTION
**Pull request by DarthHater**
I rule and have completed some work on Case Manager that's ready for review!

This PR moves the project to using Ruby 2.4.1 and due to necessity, Rails 4.2.8

This pull request makes the following changes:
* Updates Gemfile to 2.4.1
* Updates Rails to 4.2.8 and associated dependencies 
* Updates bin/spring to remove a deprecation warning
* Updates newrelic_rpm to newest to remove a slew of deprecation warnings
* Updates circle CI to use 2.4.1
* Updates Dockerfile to use Alpine 2.4.1
* Updates docs to mention we use Ruby 2.4.0

Rationale:
* Mainly a tech debt thing, it's good to stay on top of versions to patch security holes, etc...
* Ruby 2.4.0 is rumored to be faster due to hash improvements, and it simplifies a few other things (particularly with using Integers)

### CODE REVIEW

**Comment by colinxfleming** [comment]
@DarthHater questions about this:

* can/should we close in favor of #865 ?
* If we're interested in popping this forward, could we kill off the ruby upgrade and just go with the rails upgrade, and also run the `rails app:update`? Would that reduce the ~ pain ~ of the full on 5 upgrade?

**Comment by DarthHater** [comment]
Honestly 5 is going to be painful (maybe not the best word) no matter what.
This one was mostly dependency changes so nothing exciting, probably
doesn't derisk 5 much. I view the real excitement in this one as going to
ruby 2.4.0, I only had to upgrade rails to do that so it would be slightly
backwards just doing rails.

**Comment by colinxfleming** [comment]
Copy that! Leaving this open for the time being until things cook a little more.

**Comment by colinxfleming** [comment]
Awesomeeee. 

@DarthHater I'm almost afraid to ask but should we run `rake rails:update` as part of this, or just bump the gems?

**Comment by DarthHater** [comment]
@colinxfleming I'd hold off on that, just test it out and see how it flies so far.

**Comment by colinxfleming** [comment]
Here's my game plan: Merge this on Sunday night as is. If that works, do an app update in a separate PR.

**Comment by lwaldsc** [comment]
https://media.giphy.com/media/HChtj3gzcVsXK/giphy.gif

**Pull request closed without merging**
